apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: radiusguard
  name: radius-app
  labels:
    app: radius-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: radius-app
  template:
    metadata:
      name: radius-app
      labels:
        app: radius-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k8s-1
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - radius-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: radius-app
          image: docker.io/freeradius/freeradius-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1812
              protocol: UDP
            - containerPort: 1813
              protocol: UDP
          resources:
            requests:
              cpu: "100m"
              memory: "500M"
            limits:
              cpu: "100m"
              memory: "500M"
          volumeMounts:
            - mountPath: /etc/raddb/clients.conf
              name: client-conf
              subPath: clients.conf
            - mountPath: /etc/raddb/mods-enabled/sql
              name: radius-sql-config
              subPath: sql.conf
            - mountPath: /etc/raddb/radiusd.conf
              name: radiusd-conf
              subPath: radiusd.conf
      volumes:
        - name: client-conf
          configMap:
            name: radius-config
            items:
              - key: clients.conf
                path: clients.conf
        - name: radius-sql-config
          configMap:
            name: radius-sql-config
            items:
              - key: sql.conf
                path: sql.conf
        - name: radiusd-conf
          configMap:
            name: radius-sql-config
            items:
              - key: radiusd.conf
                path: radiusd.conf

      restartPolicy: Always
