apiVersion: apps/v1
kind: Deployment
metadata:
  name: radius-tool
  labels:
    app: radius-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radius-tool
  template:
    metadata:
      name: radius-tool
      labels:
        app: radius-tool
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-1
      containers:
        - name: radius-tool
          image: docker.io/hsuan1117/radius-tool:latest
          imagePullPolicy: Always
          command:
            - "sleep"
            - "infinity"
      restartPolicy: Always
