apiVersion: apps/v1
kind: Deployment
metadata:
  name: radius-tool
  labels:
    app: radius-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radius-tool
  template:
    metadata:
      name: radius-tool
      labels:
        app: radius-tool
    spec:
      containers:
        - name: radius-tool
          image: docker.io/hsuan1117/radius-tool:latest
          imagePullPolicy: IfNotPresent
          command:
            - "sleep"
            - "infinity"
      restartPolicy: Always
